name: Foodgram CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Тестирование кода
    
    services:
      postgres:
        image: postgres:13.0-alpine
        env:
          POSTGRES_USER: foodgram_user
          POSTGRES_PASSWORD: foodgram_password
          POSTGRES_DB: foodgram
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Проверка репозитория
      uses: actions/checkout@v4

    - name: Установка Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        cd backend
        pip install -r requirements.txt

    - name: Проверка кода с flake8
      run: |
        cd backend
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Тестирование Django
      env:
        SECRET_KEY: test-secret-key-for-github-actions
        DEBUG: True
        USE_SQLITE: True
        POSTGRES_DB: foodgram
        POSTGRES_USER: foodgram_user
        POSTGRES_PASSWORD: foodgram_password
        DB_HOST: localhost
        DB_PORT: 5432
      run: |
        cd backend
        python manage.py test

  build_and_push_backend:
    name: Сборка и отправка backend образа
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Проверка репозитория
      uses: actions/checkout@v4

    - name: Настройка Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Вход в Docker Hub
      uses: docker/login-action@v3
      with:
        username: aJLaxzzz
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Сборка и отправка backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: aJLaxzzz/foodgram_backend:latest

  build_and_push_frontend:
    name: Сборка и отправка frontend образа
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Проверка репозитория
      uses: actions/checkout@v4

    - name: Настройка Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Вход в Docker Hub
      uses: docker/login-action@v3
      with:
        username: aJLaxzzz
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Сборка и отправка frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: aJLaxzzz/foodgram_frontend:latest
